/******* JOIN 실습 *******/
-- 1. EMPLOYEE 테이블과 DEPARTMENT 테이블을 조인해서
-- 각 직원의 이름과 그 직원이 속한 부서명 조회
--ansi
SELECT EMP_NAME AS "이름", DEPT_TITLE AS "부서명"
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE);
--oracle
SELECT EMP_NAME AS "이름", DEPT_TITLE AS "부서명"
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_ID = DEPT_CODE;

-- 2. EMPLOYEE 테이블과 DEPARTMENT 테이블을 조인해서
-- 각 직원의 이름과 그 직원이 속한 부서명, 급여 조회
--ansi
SELECT EMP_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE);
--oracle
SELECT EMP_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_ID = DEPT_CODE;

-- 3. EMPLOYEE 테이블과 SAL_GRADE 테이블을 조인해서
-- 각 직원의 이름과 급여 등급 조회
--ansi
SELECT EMPLOYEE.EMP_NAME, SAL_GRADE.SAL_LEVEL
FROM EMPLOYEE
JOIN SAL_GRADE ON (EMPLOYEE.SAL_LEVEL = SAL_GRADE.SAL_LEVEL );
/*
다른 테이블에서 컬럼명은 다르지만 서로 의미하는 바가 같은 컬럼끼리는
컬럼명1= 컬럼명A 처럼 사용할 수 있음

다른 테이블에서 컬럼명이 같을 때는 참조하는 테이블이 무엇인지 작성해줘야함
테이블명.컬럼명1 = 테이블명.컬럼명2
*/
--oracle
SELECT e.EMP_NAME, s.SAL_LEVEL
FROM EMPLOYEE e, SAL_GRADE s
WHERE e.SAL_LEVEL = s.SAL_LEVEL;


-- 각 직원의 이름과 그 직원이 속한 부서의 부서명 및 직급 조회
-- 테이블 EMPLOYEE DEPARTMENT JOB
-- ANSI
SELECT E.EMP_NAME, D.DEPT_TITLE, J.JOB_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE= D.DEPT_ID)
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE); 
/*
E.EMP_NAME , DEPT_TITLE , JOB_NAME
전지연	    인사관리부	    대리
차태연	    인사관리부	    대리
방명수	    인사관리부	    사원
*/
-- ORACLE
SELECT E.EMP_NAME, D.DEPT_TITLE, J.JOB_NAME
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPT_CODE = D.DEPT_ID
AND E.JOB_CODE = J.JOB_CODE;


-- 1. 직원의 이메일 주소와 해당 부서의 부서명 조회
-- EMPLOYEE , DEPARTMENT
SELECT E.EMAIL, D.DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID;

-- 2. 급여가 300만원 이상인 직원들의 이름과 그 직원이 속한 부서명 조회
-- EMPLOYEE , DEPARTMENT
-- SELECT: EMP_NAME, DEPT_TITLE
SELECT E.EMP_NAME, D.DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID
AND SALARY >= 3000000;

-- 3. 각 직원의 이름과 그 직원이 속한 부서명의 부서명, 급여 등급명 조회
-- EMPLOYEE , DEPARTMENT, SAL_GRADE
-- SELECT: EMP_NAME, DEPT_TITLE, SAL_LEVEL
SELECT E.EMP_NAME, D.DEPT_TITLE, S.SAL_LEVEL
FROM EMPLOYEE E, DEPARTMENT D, SAL_GRADE S
WHERE E.DEPT_CODE = D.DEPT_ID
AND e.sal_level = s.sal_level;


-- 4. 직급이 대리이면서 아시아 지역에 근무하는 직원조회
-- 사번 이름 직급명 부서명 근무지역명 급여 조회
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, D.DEPT_TITLE, L.LOCAL_NAME, E.SALARY
FROM EMPLOYEE E, DEPARTMENT D, JOB J, LOCATION L
WHERE E.DEPT_CODE = D.DEPT_ID
AND E.JOB_CODE = J.JOB_CODE
AND d.location_id = l.local_code
AND J.JOB_NAME = '대리'
AND L.LOCAL_NAME LIKE 'ASIA%';



-- 1. D5부서에 속한 직원들의 이름과 직급명 조회
-- 테이블은 EMPLOYEE JOB
SELECT E.DEPT_CODE, E.EMP_NAME, J.JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
AND E.DEPT_CODE = 'D5';


-- 2. 각 부서의 부서명과 해당 부서에 속한 직원의 평균급여 조회
-- 테이블 EMPLOYEE DEPARTMENT
-- GROUP BY, AVG
SELECT D.DEPT_TITLE, FLOOR(AVG(E.SALARY))
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID
GROUP BY D.DEPT_TITLE;


-- 3. 급여 등급이 S4이상인 직원의 이름, 급여, 급여 등급 조회
-- 테이블 EMPLOYEE SAL_GRADE
-- WHERE IN
SELECT E.EMP_NAME, E.SALARY, E.SAL_LEVEL
FROM EMPLOYEE E, SAL_GRADE S
WHERE e.sal_level = s.sal_level
AND S.SAL_LEVEL >= 'S4'; --S.SAL_LEVEL IN('S4','S5','S6');

