/******CREATE TABLE 실습*******/
/*
CREATE TABLE KH_CAFE(
    CAFE_ID NUMBER(10,0) PRIMARY KEY,
    CAFE_NAME VARCHAR2(100) NOT NULL,
    CAFE_PHONE VARCHAR2(20) CONSTRAINT CAFE_PHONE_U UNIQUE,
    CAFE_ADDRESS VARCHAR2(100),
    CONSTRAINT CAFE_ADDRESS_U UNIQUE(CAFE_ADDRESS)
    );
*/
-- 고객테이블 CUSTOMER
CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER(10,0) PRIMARY KEY,
CUSTOMER_NAME VARCHAR2(100) NOT NULL,
CUSTOMER_EMAIL VARCHAR2(100) CONSTRAINT CUSTOMER_EMAIL_U UNIQUE,
CUSTOMER_PHONE VARCHAR2(20),
CONSTRAINT CUSTOMER_PHONE_U UNIQUE(CUSTOMER_PHONE),
CUSTOMER_ADDRESS VARCHAR2(255)
);

COMMENT ON COLUMN "CUSTOMER".CUSTOMER_ID IS '고객아이디'; --주석작성
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_NAME IS '고객이름';
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_EMAIL IS '고객이메일';
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_PHONE IS '고객핸드폰번호';
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_ADDRESS IS '고객주소';

COMMIT;




--PRODUCT 테이블 생성
CREATE TABLE PRODUCT (
PRODUCT_ID NUMBER(10,0) CONSTRAINT P_I_P PRIMARY KEY,
PRODUCT_NAME VARCHAR2(100) NOT NULL,
PRODUCT_PRICE NUMBER(10,2) NOT NULL,
PRODUCT_DESC VARCHAR2(200) CONSTRAINT PRODUCT_DESC_U UNIQUE
);
COMMIT;

INSERT INTO PRODUCT VALUES (1,'아메리카노',3000,'신선한 원두로 만든 아메리카노');
INSERT INTO PRODUCT VALUES (2,'카페라떼',2500,'부드러운 우유가 들어간 라떼');
INSERT INTO PRODUCT VALUES (3,'카푸치노',3500,'진한 커피와 거품이 어우러진 카푸치노');
INSERT INTO PRODUCT VALUES (4,'카라멜마키아토',4000,'달콤한 카라멜 시럽이 들어간 마키아토');
COMMIT;















